name: Auto label

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  pull_request_target

jobs:
  label:
    runs-on: ubuntu-20.04
    steps:
      - name: Auto Label
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4.3.0
        with:
          configuration-path: .github/auto-label.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
